import Head from 'next/head';
import Image from 'next/image';

import Timer from '../components/timer';
import { useTimer } from '../contexts/TimerContext';
import { useEffect, useState } from 'react';

import { TypeTimer } from '../@types/TypeTimer';
import { api } from '../services/api';

import SideBar from '../components/sidebar';
import styles from '../styles/Home.module.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

import Navbar from '../components/navbar';
import TimerTable from '../components/TimerTable';
import { CurrentTimer } from '../@types/CurrentTimer';
import nextId, { setPrefix } from 'react-id-generator';

type HomeProps = {
	listOfTimers: TypeTimer[];
};

const timerDemo = {
	name: 'ReactJS',
	duration: {
		hours: 0,
		minutes: 56,
		seconds: 50,
	},
	minutesBeforeInterval: 25,
	interval: 5,
	editableDuration: 25 * 60,
	intervalMode: false,
};

export default function Home(props) {
	// const tim = use
	const { setTimerList, handleCurrentTimerPlay, isExecuting, hasNextTimer, clearExecuteState } = useTimer();

	const [collapsed, setCollapsed] = useState(false);
	const [rtl, setRtl] = useState(false);
	const [image, setImage] = useState(true);
	const [toggled, setToggled] = useState(null);

	setPrefix('');

	useEffect(() => {
		const tempTimer = { ...timerDemo, id: Number.parseInt(nextId()) };
		setTimerList([tempTimer]);
		handleCurrentTimerPlay(tempTimer);
	}, []);

	//

	function handleTimerEnded() {
		if (hasNextTimer) {
			setTimeout(() => {
				// setCurrentTimer(executeNext());
			}, 2000);
		} else {
			clearExecuteState();
		}
	}

	const handleCollapsedChange = (checked) => {
		setCollapsed(checked);
	};

	const handleRtlChange = (checked) => {
		setRtl(checked);
	};

	const handleToggleSidebar = (value) => {
		setToggled(value);
	};

	return (
		<div className={`${styles.container} ${rtl ? 'rtl' : ''} ${toggled ? 'toggled' : ''}`}>
			<Head>
				<title>STIMER</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/images/favicon.png" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<SideBar
				handleCollapsedChange={handleCollapsedChange}
				rtl={rtl}
				collapsed={collapsed}
				toggled={toggled}
				handleToggleSidebar={handleToggleSidebar}
			/>

			<main className={styles.main}>
				<Navbar
					collapsed={collapsed}
					handleCollapsedChange={handleCollapsedChange}
					rtl={rtl}
					handleRtlChange={handleRtlChange}
					handleToggleSidebar={handleToggleSidebar}
					toggled={toggled}
				/>
				<div
					className={styles.content}
					
				>
					<Timer />
					<TimerTable />
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				></a>
			</footer>
		</div>
	);
}
